[package]
name = "acpica"
version = "0.1.1"
edition = "2021"
authors = ["Jason Qin"]
description = "The greatest rewrite of ACPICA ever"

[dependencies]
uefi = "0.16.0"
pasts = { version = "0.11.0", default-features = false }
spin = "0.9.3"
lazy_static = "*"
